//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BquizDB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bq_Answer
    {
        public System.Guid TestId { get; set; }
        public System.Guid QuestionId { get; set; }
        public byte Answer { get; set; }
    
        public virtual bq_Question bq_Question { get; set; }
        public virtual bq_Test bq_Test { get; set; }
    }
}
