//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BquizDB.Entities
{
    using System;
    
    public partial class bq_Test_GetById_Result1
    {
        public System.Guid TestId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid QuizId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Mark { get; set; }
    }
}
