//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BquizDB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bq_Test
    {
        public bq_Test()
        {
            this.bq_Answer = new HashSet<bq_Answer>();
        }
    
        public System.Guid TestId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid QuizId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Mark { get; set; }
    
        public virtual ICollection<bq_Answer> bq_Answer { get; set; }
        public virtual bq_Quiz bq_Quiz { get; set; }
        public virtual bq_User bq_User { get; set; }
    }
}
